# Autogenerated wrapper script for Aprepro_jll for aarch64-linux-gnu-cxx11
export aprepro_exe, libaprepro_lib

JLLWrappers.@generate_wrapper_header("Aprepro")
JLLWrappers.@declare_library_product(libaprepro_lib, "libaprepro_lib.so.2")
JLLWrappers.@declare_executable_product(aprepro_exe)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libaprepro_lib,
        "lib/libaprepro_lib.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aprepro_exe,
        "bin/aprepro",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
