# Autogenerated wrapper script for Aprepro_jll for x86_64-w64-mingw32-cxx03
export aprepro_exe, libaprepro_lib

JLLWrappers.@generate_wrapper_header("Aprepro")
JLLWrappers.@declare_library_product(libaprepro_lib, "libaprepro_lib.dll")
JLLWrappers.@declare_executable_product(aprepro_exe)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libaprepro_lib,
        "bin\\libaprepro_lib.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aprepro_exe,
        "bin\\aprepro.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
